### ISSUE TITLE
Installed GCC by setup-gcc not set to default GCC

### ISSUE THREAD

**Issue by CGarces** [egor-tensin/setup-gcc#3]
I'm trying to implement a build matrix for gcc [9,10,11]

The striped version of my workflow is something like this

```yaml
  build:
    needs: commontasks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: 
        gcc_version: [9,10,11]
    steps:
    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: ${{matrix.gcc_version }}
    - uses: actions/checkout@v2
    - name: build
      run: gcc --version

```
My expectation is receive a different value for **gcc --version** on each build stage but I always get "gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0" that is the one installed by default on 20.04

The full workflow is at 
https://github.com/Mange/rtl8192eu-linux-driver/blob/test_gcc/.github/workflows/build.yml

For example this logs are for GCC 11 and 10 but both shows "9.3.0"
https://github.com/Mange/rtl8192eu-linux-driver/runs/3517256317?check_suite_focus=true
https://github.com/Mange/rtl8192eu-linux-driver/runs/3517256332?check_suite_focus=true
